### ISSUE TITLE
GUI Base Setup

### ISSUE THREAD

**Issue by ramirez915** [SIGBlockchain/project_red#25] opened 2020-02-10 04:05 UTC
Branch: `gui_base`

We need to have a base set up for the GUI, something basic that we can start with and modify as we go. Using JavaFX Scene Builder, create a grid pane (a 2x3 is fine for now) that will contain these 3 components for now:
- 2 `Label` components that will contain the account balance and wallet address
- 1 `Button` component that will be used to refresh the scene

Give each component a meaningful `fx:id` and `text` (`fx:id` found under the code panel, `text` found under properties).
Leave the top row of the grid empty as we are going to use it for something else and populate the other rows with these components.

To get started:

- [x] Try running the gui successfully.

- [x] Then go into the **gui** folder to find the **scene.fxml** file under **resources**. In the fxml file go to the scene builder and replace whats there with the grid pane

- [x]  Add the components with an appropriate `fx:id` and `text`

- [x]  Add the components to the `Controller` class with the `@FXML` annotation (like whats already there)

- [x] Replace `initialize()` with a simple function that contains `System.out.println( anything here)` for the button

- [x] Bind the new function that returns nothing to the button (done under code on scene builder)

- [x]  Visually test

This is a good resource to check out to manually fix things if scene builder is going weird.
https://www.vojtechruzicka.com/javafx-fxml-scene-builder/

Also in my experience with scene builder, if the drop down menus don't seem to work try closing out of the project and opening it again. It is something weird I don't understand but is a quick fix for me

**Comment by Akshantjain** [comment] 2020-02-10 06:40
@ramirez915 
Why don't we use disabled textFields instead of labels?
I will look attractive than labels and will be easier to change the values inside it with a prompt text until the refresh button is pressed. I have done this in earlier projects as well.
I have made one! Have a look...
<img width="614" alt="Screen Shot 2020-02-10 at 12 40 09 AM" src="https://user-images.githubusercontent.com/34630484/74126582-e872ae80-4b9d-11ea-8e9a-a974cbea4081.png">

**Comment by ramirez915** [comment] 2020-02-11 02:13
I don't see why not, lets do it like this for now! I approve of this idea. Great job @Akshantjain !!!

**Comment by Akshantjain** [comment] 2020-02-11 02:14
Could u fix some issue in the pull request?
I am not able to fix it.

**Comment by ramirez915** [comment] 2020-02-11 02:16
What issue are you running into?

**Comment by Akshantjain** [comment] 2020-02-11 04:07
This is what happening.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34630484/74210487-97bc8d80-4c51-11ea-80fc-b0881b438f70.png">

I need to figure this out what i am doing wrong...maybe i am running the wrong main class for java application.

**Comment by Vineet77** [comment] 2020-02-12 15:06
In order to the run the application, you need to do `.\gradlew run`

**Comment by Akshantjain** [comment] 2020-02-14 02:02
The issue is solved and the pull request has been approved.
Just the pull request is to be merged to the dev branch.

**Closed as completed by Akshantjain** 2020-02-14 02:02 UTC
